version: '3.8'

name: reiverr-dev

services:
  reiverr-frontend:
    container_name: reiverr-dev
    image: ghcr.io/nikusernik/reiverr:latest
    restart: unless-stopped
    volumes:
      - ./backend/config:/usr/src/app/config
